{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone.secretName" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
type: Opaque
stringData:
  PG_PASSWORD: {{ .Values.secrets.pgPassword | quote }}
  GRAFANA_ADMIN_PASSWORD: {{ .Values.secrets.grafanaAdminPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  JWT_JWKS_URL: {{ .Values.secrets.jwtJwksUrl | quote }}
  JWT_AUDIENCE: {{ .Values.secrets.jwtAudience | quote }}
  JWT_ISSUER: {{ .Values.secrets.jwtIssuer | quote }}
{{- end }}
